  # Database connection configuration
  spring:
    datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ecommerce
      username: ${MYSQL_USER:student}
      password: ${MYSQL_PASSWORD:student}

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  # spring:
  #   config:
  #     import: "optional:file:./local.env"
  #   datasource:
  #     url:  "jdbc:mysql://localhost:3306/ecommerce"
  #     username: root
  #     password:  1234567890
  #   jpa:
  #     hibernate:
  #       ddl-auto: update
  #     show-sql: true


  payment:
    vnPay:
      url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      tmnCode: "B392S5MZ"
      secretKey: "GIGCQNW0JPP8IW4OM6CURR1M8R1EAUZ7"
      returnUrl: "http://192.130.38.105:8080/api/v1/payment/vnpay-callback"
      version: "2.1.0"
      command: "pay"
      orderType: "other"

  jwt:
    secret: "d83hfsdfsfdfs9e32r23fwfshfsdhfsdfskjfsdfsd343432sdffsdfdsf"
    expiration: 36000000
    refresh-secret: "d83sfdsdfsdfwrioewfjjjjewrw3246238948nfdsf889fsd89sdf"
    refresh-expiration: 86400000
  base64:
    key : "q2ert0yu3iopasdf5gvzjl"