  # Database connection configuration
#spring:
#datasource:
#  url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ecommerce
#  username: ${MYSQL_USER:root}
#  password: ${MYSQL_PASSWORD:1234567890}
#
#  jpa:
#   hibernate:
#     ddl-auto: update
#   show-sql: true
  spring:
    config:
      import: "optional:file:./local.env"
    datasource:
      url:  "jdbc:mysql://localhost:3306/ecommerce"
      username: root
      password:  1234567890
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  payment:
    vnPay:
      url: ${PAY_URL}
      tmnCode: ${TMN_CODE}
      secretKey: ${SECRET_KEY}
      returnUrl: ${RETURN_URL}
      version: ${VERSION}
      command: ${COMMAND}
      orderType: ${ORDER_TYPE}

  jwt:
    secret: "d83hfsdfsfdfs9e32r23fwfshfsdhfsdfskjfsdfsd343432sdffsdfdsf"
    expiration: 36000000
    refresh-secret: "d83sfdsdfsdfwrioewfjjjjewrw3246238948nfdsf889fsd89sdf"
    refresh-expiration: 86400000
